### ISSUE TITLE
Doesn't working

### ISSUE THREAD

**Issue by senyamac** [adascal/kinopub.webos#24]
Добрый день.

Установил ваше приложение, но при запуске только черный экран.

К интернету подключен через Ethernet.

Можете что-то подсказать по этой проблеме?

Версия WebOS: 05.80.65
Телевизор: UJ639V

**Comment by senyamac** [comment]
Версия webos 3.5 написано в интернете, видимо поэтому.

**Comment by adascal** [comment]
Всё так, согласно https://www.lg.com/ru/televisions/lg-43UJ639V там webOS 3.5
05.80.65 - это версия прошивки, скорее всего

**Comment by senyamac** [comment]
@adascal Доработки под Enyo нет в планах?

**Comment by adascal** [comment]
Нет, и Enyo больше не поддерживается
