### ISSUE TITLE
app launches but tv screen blacked out

### ISSUE THREAD

**Issue by epspi** [adascal/kinopub.webos#4]
Model: 60UH6035-UC
Software Version: 05.60.03
webOS TV Version: 3.4.0-5803 (dreadlocks-digya)

Is it not compatible with enact?
![image](https://user-images.githubusercontent.com/8306014/112708727-20b07b80-8e8a-11eb-9ad9-54194ed9ce1f.png)

**Comment by adascal** [comment]
Unfortunately app wouldn't work WebOS v3, minimal supported version is WebOS v4 😔

**Comment by adascal** [comment]
I've tried to add support, but without real device it's a bit complicated

**Comment by PiRomant** [comment]
Changing base give apportunity to supports a lot of modern Smart TV and STB platforms and also some legacy but high-demand platforms, which allows you to deliver your application to a wide number of devices.
https://github.com/vitalets/awesome-smart-tv#cross-platform-frameworks

**Comment by adascal** [comment]
I know about such solutions. But cause it initially was simple pet project just for my own need... It wasn't a goal to support multiple platforms :)
Maybe I'll move to `react-tv` later. Will see
