### ISSUE TITLE
Постоянная реактивация устройства

### ISSUE THREAD

**Issue by chipx** [adascal/kinopub.webos#52]
Телевизор LG WebOS 5.2.3-252109
1. Установил через MediaStationX (0.1.138 (lg)) и netlify
2. На экране выводится код для активации.
3. Ввожу код на сайте и на телевизоре происходит загрузка контента.
4. Через несколько секунд опять появляется экран с активацией устройства.
5. Повторная активация не помогает.

**Comment by adascal** [comment]
Должно пофикситься последним коммитом
